// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwuCYTTvH50fabAvE83CuQ1rHMVQfVS3c',
    appId: '1:359218122786:web:f4ea252e8e24b95abbba7b',
    messagingSenderId: '359218122786',
    projectId: 'youtube-api-401500',
    authDomain: 'api-401500.firebaseapp.com',
    storageBucket: 'youtube-api-401500.appspot.com',
    measurementId: 'G-3DWJPD8F2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SwATAGzXUz4r1-KjlWjNYlDlSItWxsc',
    appId: '1:359218122786:android:b73f6a0f5a9a5efdbbba7b',
    messagingSenderId: '359218122786',
    projectId: 'youtube-api-401500',
    storageBucket: 'youtube-api-401500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmxrAlgIt8LBQPVlOr6Dt6aUlyVwmYYKc',
    appId: '1:359218122786:ios:55a39097b7dd785fbbba7b',
    messagingSenderId: '359218122786',
    projectId: 'youtube-api-401500',
    storageBucket: 'youtube-api-401500.appspot.com',
    iosBundleId: 'com.example.youtubeRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmxrAlgIt8LBQPVlOr6Dt6aUlyVwmYYKc',
    appId: '1:359218122786:ios:57f57af97a0e2c5dbbba7b',
    messagingSenderId: '359218122786',
    projectId: 'youtube-api-401500',
    storageBucket: 'youtube-api-401500.appspot.com',
    iosBundleId: 'com.example.youtubeRecipe.RunnerTests',
  );
}
